apiVersion: apps/v1
kind: Deployment
metadata:
    name: packaging-delivery-svc-deployment
    labels:
      app: packaging-delivery-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: packaging-delivery-svc      
  template:
    metadata:
      labels:
        app: packaging-delivery-svc
    spec:
      containers:
        - name: packaging-delivery-svc
          image: returnordercr.azurecr.io/packaginganddeliverysvcimage:latest
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: returnordersvcsecret

---

apiVersion: v1
kind: Service
metadata:
  name: packaging-delivery-svcservice
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
      app: packaging-delivery-svc      
    
    